### ISSUE TITLE
Tab component

### ISSUE THREAD

**Issue by jantolg** [GeographicaGS/Latitude#13]
In scopes-www there is a component based on tabs behaviour, maybe it could be useful to include it at latitude
![tab component](https://user-images.githubusercontent.com/17105273/33550828-9b9f37e0-d8ef-11e7-83f8-5a1dfeb51cb8.jpg)

See more at: [scope-www](https://github.com/GeographicaGS/scopes-www/tree/dev-www/src/app/common/tab)

**Comment by eamador** [comment]
@jantolg we've already included a tab-component in the latitude package (https://github.com/GeographicaGS/Latitude/tree/master/src/components/ui/tab-navigation) but as you can see, this component seems to be much simpler than the one you are mentioning, so we could place yours instead of the current latitude's one.

If you would like to do it yourself i would be happy to review the PR. We just need to make sure that this will not break any project that uses the current latitude-tab-component, like in reveal-www for instance.

If you have no time for this, i could do it myself once i come back from holidays (i start today and comeback on the 18december).

Thanks for the suggestion :D
